# Generated by Django 4.2.4 on 2023-08-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',), 'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
    ]
